//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Post
    {
        public E_Post()
        {
            this.E_Comment = new HashSet<E_Comment>();
            this.E_PostImage = new HashSet<E_PostImage>();
            this.E_PostTag = new HashSet<E_PostTag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortContent { get; set; }
        public string PostContent { get; set; }
        public int CategoryID { get; set; }
        public int ViewCount { get; set; }
        public string SeoLink { get; set; }
        public bool Slider { get; set; }
        public bool Area1 { get; set; }
        public bool Area2 { get; set; }
        public bool Area3 { get; set; }
        public bool Notification { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime addDate { get; set; }
        public int AddUserID { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual E_Category E_Category { get; set; }
        public virtual ICollection<E_Comment> E_Comment { get; set; }
        public virtual E_User E_User { get; set; }
        public virtual ICollection<E_PostImage> E_PostImage { get; set; }
        public virtual ICollection<E_PostTag> E_PostTag { get; set; }
    }
}
