//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ProcessType
    {
        public E_ProcessType()
        {
            this.E_Log_Table = new HashSet<E_Log_Table>();
        }
    
        public int ID { get; set; }
        public string ProcessName { get; set; }
    
        public virtual ICollection<E_Log_Table> E_Log_Table { get; set; }
    }
}
