//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_User
    {
        public E_User()
        {
            this.E_Address = new HashSet<E_Address>();
            this.E_Ads = new HashSet<E_Ads>();
            this.E_Category = new HashSet<E_Category>();
            this.E_Comment = new HashSet<E_Comment>();
            this.E_Contact = new HashSet<E_Contact>();
            this.E_FavLogoTitle = new HashSet<E_FavLogoTitle>();
            this.E_Log_Table = new HashSet<E_Log_Table>();
            this.E_Meta = new HashSet<E_Meta>();
            this.E_Post = new HashSet<E_Post>();
            this.E_PostImage = new HashSet<E_PostImage>();
            this.E_PostTag = new HashSet<E_PostTag>();
            this.E_SocialMedia = new HashSet<E_SocialMedia>();
            this.E_Video = new HashSet<E_Video>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NameSurName { get; set; }
        public string ImagePath { get; set; }
        public bool isAdmin { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime addDate { get; set; }
        public int LastUpdateUserID { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        public virtual ICollection<E_Address> E_Address { get; set; }
        public virtual ICollection<E_Ads> E_Ads { get; set; }
        public virtual ICollection<E_Category> E_Category { get; set; }
        public virtual ICollection<E_Comment> E_Comment { get; set; }
        public virtual ICollection<E_Contact> E_Contact { get; set; }
        public virtual ICollection<E_FavLogoTitle> E_FavLogoTitle { get; set; }
        public virtual ICollection<E_Log_Table> E_Log_Table { get; set; }
        public virtual ICollection<E_Meta> E_Meta { get; set; }
        public virtual ICollection<E_Post> E_Post { get; set; }
        public virtual ICollection<E_PostImage> E_PostImage { get; set; }
        public virtual ICollection<E_PostTag> E_PostTag { get; set; }
        public virtual ICollection<E_SocialMedia> E_SocialMedia { get; set; }
        public virtual ICollection<E_Video> E_Video { get; set; }
    }
}
