//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENGINEERSEntities : DbContext
    {
        public ENGINEERSEntities()
            : base("name=ENGINEERSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<E_Address> E_Address { get; set; }
        public DbSet<E_Ads> E_Ads { get; set; }
        public DbSet<E_Category> E_Category { get; set; }
        public DbSet<E_Comment> E_Comment { get; set; }
        public DbSet<E_Contact> E_Contact { get; set; }
        public DbSet<E_FavLogoTitle> E_FavLogoTitle { get; set; }
        public DbSet<E_Log_Table> E_Log_Table { get; set; }
        public DbSet<E_Meta> E_Meta { get; set; }
        public DbSet<E_Post> E_Post { get; set; }
        public DbSet<E_PostImage> E_PostImage { get; set; }
        public DbSet<E_PostTag> E_PostTag { get; set; }
        public DbSet<E_ProcessType> E_ProcessType { get; set; }
        public DbSet<E_SocialMedia> E_SocialMedia { get; set; }
        public DbSet<E_User> E_User { get; set; }
        public DbSet<E_Video> E_Video { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
